# Generated by Django 2.2.1 on 2019-07-28 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=1000)),
                ('commentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Board')),
            ],
        ),
    ]
